import json
import os
from typing import Any, List
from agents.agent_utils.helper import tensor_to_base64_image

from agents.unaware_vlm_llm_agent import UnawareVLMAgent

FOLDER = "./prompt"
PROMPT_FILE = "alfworld_3prompts_revised.json"
with open(os.path.join(FOLDER, PROMPT_FILE), "r") as f:
    d = json.load(f)


class AwareVLMAgent(UnawareVLMAgent):
    def __init__(self, llm_model, vlm_model, num_eval: int):
        super().__init__(llm_model=llm_model, vlm_model=vlm_model, num_eval=num_eval)
        # assert vlm_model in ['gpt-4o', 'gpt-4o-mini', 'gpt-4-vision-preview'], "VLM should be chosen from gpt-4o, gpt-4o-mini and gpt-4-vision-preview."
        # self.llm_model = llm_model
        # self.vlm_model = vlm_model
        # self.llm_engine = OpenAIEngine(model=llm_model)
        # self.vlm_engine = OpenAIEngine(model=vlm_model)
        self.name = "AwareVLMAgent"
        self.logger = self.set_logger(name=self.name)

    # def observe(self, observation) -> str:
    #     self.obs_memory.append(observation)
    #     conversation = self.generate_query_for_vlm()
    #     vlm_obs = self.vlm_engine.generate(conversation=conversation)

    #     self.add_to_memory(label='observation', value=vlm_obs)
    #     return vlm_obs

    def init_prompts(self):
        self.prompts = {
            "vlm_prompt": (
                "You are a visual assistant designed to help an agent perceive its environment and complete household tasks. "
                "The environment consists of uniquely identified receptacles and objects, named using their type and numerical ID. Examples:\n"
                '- "Countertop 1" refers to a receptacle of type "countertop" with ID 1.\n'
                '- "Apple 2" refers to an object of type "apple" with ID 2.\n\n'
                "Objects and receptacles are segmented and labeled in the agent's first-person view. For instance:\n"
                '- "Object Bindings: 1--countertop 1, 3--apple 2" indicates that segment 1 corresponds to "countertop 1," and segment 3 corresponds to "apple 2."\n\n'
                'Always refer to objects and receptacles by their exact names (e.g., "countertop 1," "apple 2") from the object bindings, avoiding segmentation numbers. '
                "Use the agent's history of thoughts, actions, and previous observations generated by you to determine the current state of task-relevant objects and receptacles.\n\n"
                "Your responsibilities include:\n"
                "1. **Identify the Held Item**: Determine and describe the object the agent is holding. The held item will:\n"
                "- Always appear at the bottom center of the view, closer to you than other objects, and floating in the air.\n"
                '- Be held only if previous actions include "take [object] from [receptacle]."\n'
                '- No longer be held if the previous action includes "put [object] in/on [receptacle]."\n'
                "Verify these conditions before concluding whether the agent is holding an object.\n\n"
                "2. **Previous Action Effect**: Explain the impact of the agent's most recent action on the environment or objects.\n\n"
                "3. **Describe Spatial Relationships**: Identify and describe spatial relationships between task-relevant objects and receptacles in the environment.\n\n"
                "4. **Indicate Receptacle Status**: Specify the status (open or closed) of task-relevant receptacles such as fridges, safes, drawers, cabinets, or microwaves. If these receptacles are not visible, do not comment on their status.\n\n"
                "Generate your response based on:\n"
                "- Visual observations\n"
                "- Agent's thought and action history\n"
                "- Task objectives\n\n"
                'Combine all observations into a single concise sentence, addressing the agent directly using "you." For example:\n'
                '- "You are holding an apple (2). On countertop 1, you see microwave 1. Microwave 1 is closed."\n'
                'If no objects or receptacles are visible, output: "You see nothing."\n\n'
                "Follow these principles to provide accurate, task-relevant assistance."
            ),
            "llm_prompt": "Interact with a household to solve a task. Here are two examples.\n"
            + d[f"react_{self.task_type}_1"]
            + d[f"react_{self.task_type}_0"],
        }

    def generate_query_for_vlm(self) -> List[Any]:
        s = self.prompts["vlm_prompt"]
        s += f"\nHere is the task and agent's history of thoughts, actions and previous observations generated by you:\n{self.task_info}\n"
        for i, item in enumerate(self.response_memory):
            if item["label"] == "response":
                s += f'> {item["value"]}'
            elif item["label"] == "observation":
                s += item["value"]
            if i != len(self.response_memory) - 1:
                s += "\n"

        cur_obs = self.obs_memory[-1]
        vlm_query = []
        vlm_query.append(
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": s
                        + "\nFollowing is current visual observation along with object bindings, generate your response according to the instructions.\n",
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{tensor_to_base64_image(cur_obs['image'])}"
                        },
                    },
                    {"type": "text", "text": cur_obs["object_bindings"]},
                ],
            }
        )

        return vlm_query
