# load prompts
with open("./prompt/observer_prompts.txt", "r") as f:
    observer_one_shot_prompt = f.read()

observer_context = (
    "You are a perception module of an intelligent agent to perceive its environment in simulated household environment. "
    "The simulated household environment consists of objects and receptacles. Each object and receptacle is uniquely identified by its type and numerical ID. For example, 'apple 2' refers to an object of type 'apple' with ID 2. 'countertop 1' refers to a receptacle of type 'countertop' with ID 1. "
    "Every timestep, you will receive the agent's observation of the environment. Observation will include the first-person view image, the object bindings, and the inventory. "
)

observer_single_image_bbox = (
    "The first-person view image will have bounding boxes around the objects and receptacles in the environment. "
    "The label of the bounding box will appear on the top left corner of the bounding box. "
    "The object bindings will provide the information of what object or receptacle each bounding box corresponds to. For example, 'Object Bindings: 1--countertop 1, 3--apple 2' indicates that in the current image, bounding box 1 corresponds to 'countertop 1', and bounding box 3 corresponds to 'apple 2'."
    "The inventory will provide the information of what object and the status of the object the agent is holding. For example, if you are holding an apple that has been heated, the inventory will be 'Inventory: You are holding a hot apple 1.' if you are not holding anything, the inventory will be 'Inventory: You are not holding anything'."
    "You will be given the agent's history of actions, previous textual observations generated by you and observation of this timestep."
)

observer_single_image_seg = (
    "The first-person view image will have colored segments of the image that correspond to the objects and receptacles in the environment. "
    "The label of the segment will appear on the center of the segment. "
    "The object bindings will provide the information of what object or receptacle each segment corresponds to. For example, 'Object Bindings: 1--countertop 1, 3--apple 2' indicates that in the current image, segment 1 corresponds to 'countertop 1', and segment 3 corresponds to 'apple 2'."
    "The inventory will provide the information of what object and the status of the object the agent is holding. For example, if you are holding an apple that has been heated, the inventory will be 'Inventory: You are holding a hot apple 1.' if you are not holding anything, the inventory will be 'Inventory: You are not holding anything'."
    "You will be given the agent's history of actions, previous textual observations generated by you and observation of this timestep."
)

observer_double_image_bbox = (
    "The first-person view image will have bounding boxes around the objects and receptacles in the environment. "
    "The label of the bounding box will appear on the top left corner of the bounding box. "
    "The object bindings will provide the information of what object or receptacle each bounding box corresponds to. For example, 'Object Bindings: 1--countertop 1, 3--apple 2' indicates that in the current image, bounding box 1 corresponds to 'countertop 1', and bounding box 3 corresponds to 'apple 2'."
    "The inventory will provide the information of what object and the status of the object the agent is holding. For example, if you are holding an apple that has been heated, the inventory will be 'Inventory: You are holding a hot apple 1.' if you are not holding anything, the inventory will be 'Inventory: You are not holding anything'."
    "You will be provided with the agent's action history, previously generated textual observations, the observation from the previous timestep (if available), and the current timestep's observation."
    "You can compare the current timestep's observation with the previous timestep's observation to generate the textual observation."
)

observer_double_image_seg = (
    "The first-person view image will have colored segments of the image that correspond to the objects and receptacles in the environment. "
    "The label of the segment will appear on the center of the segment. "
    "The object bindings will provide the information of what object or receptacle each segment corresponds to. For example, 'Object Bindings: 1--countertop 1, 3--apple 2' indicates that in the current image, segment 1 corresponds to 'countertop 1', and segment 3 corresponds to 'apple 2'."
    "The inventory will provide the information of what object and the status of the object the agent is holding. For example, if you are holding an apple that has been heated, the inventory will be 'Inventory: You are holding a hot apple 1.' if you are not holding anything, the inventory will be 'Inventory: You are not holding anything'."
    "You will be provided with the agent's action history, previously generated textual observations, the observation from the previous timestep (if available), and the current timestep's observation."
    "You can compare the current timestep's observation with the previous timestep's observation to generate the textual observation."
)

observer_task_info = (
    "Your goal is to generate informative textual observations of these objects and receptacles of the latest first-person view image based on the agent's history of actions and previous observations generated by you to help the agent complete household tasks. "
    "To successfully generate an informative textual observation, in your response, you should include:\n"
    "1. **Previous Action Effect**: Explain the impact of the agent's most recent action on the environment or objects.\n"
    "- If you think the action failed, you should say 'Nothing happens'.\n"
    "2. **Describe Spatial Relationships**: Identify and describe spatial relationships between task-relevant objects and receptacles in the environment.\n"
    " - Only pay attention to on/in relationships. Don't mention other relationships.\n"
    "3. **Indicate Receptacle Status**: Specify the status (open or closed) of receptacles such as fridges, safes, drawers, cabinets, or microwaves. If these receptacles are not visible, do not comment on their status.\n"
)

observer_rules_prompt = (
    "Note that the item of inventory will:\n"
    "- Always appear at the bottom center of the view, closer to you than other objects, and floating in the air.\n"
    "It is important to follow the following rules to generate an textual observation:\n"
    " - Structure your response as a paragraph.\n"
    ' - Addressing the agent directly using "you."\n'
    ' - Always start with "Observation:"\n'
    " - Only describe the objects and receptacles that are provided in the object bindings.\n"
    " - when mentioning the object and receptacle, always mention the type and id of the object and receptacle.\n"
    " - Don't mention the item of inventory in your observation.\n"
    ' - Respond in this format: "Observation: <Previous action effect> if the agent has performed an action. <Describe spatial relationships>. <Indicate receptacle status> if the receptacle is open or closed."\n'
)


def generate_prompts_for_observer(perception_type, is_double_image):
    # Build common suffix once
    common_suffix = (
        observer_task_info + observer_rules_prompt + observer_one_shot_prompt
    )

    # Select image type based on parameters
    if perception_type == "bbox":
        image_type = (
            observer_double_image_bbox
            if is_double_image
            else observer_single_image_bbox
        )
    elif perception_type == "segs":
        image_type = (
            observer_double_image_seg if is_double_image else observer_single_image_seg
        )

    return observer_context + image_type + common_suffix


def generate_prompts_for_evaluator(vlm_obs, ground_truth_obs):
    sys_prompt = (
        "Please evaluate the following VLM-generated observation in comparison to the ground truth on the following two aspects:\n"
        # "1. Correctness of identifying whether the agent is holding something, and if so, correctly specifying what is being held.\n"
        # " - If the agent is holding an object, only when vlm correctly identifies the agent is holding an object, and correctly identifies the object, the score is 1, otherwise the score is 0.\n"
        # " - If the agent is not holding an object, only when vlm correctly identifies the agent is not holding an object, the score is 1, otherwise the score is 0.\n"
        "1. Accuracy of describing spatial relationships between objects and receptacles.\n"
        " - Only pay attention to on/in relationships. First identify how many such relationships are in the ground truth observation, then identify how many such correct relationships are in the vlm observation. The score is the number of correctly identified relationships divided by the total number of such relationships.\n"
        ' - e.g. if the ground truth observation says "On countertop 1, you can see apple 2 and pen 1. In drawer 3, you can see watch 1." Then there is 3 on/in relationships in the ground truth observation, (apple 2, countertop 1), (pen 1, countertop 1), (watch 1, drawer 3). If the vlm observation says "On countertop 1, you can see apple 2. In drawer 3, you can see watch 1 and pen 1." Then there is 2 correctly identified on/in relationships(pen 1 is not correctly identified) in the vlm observation, (apple 2, countertop 1), (watch 1, drawer 3). The score is 2/3 because only 2 out of 3 on/in relationships are correctly identified.\n'
        ' - e.g. if the ground truth observation says "On countertop 1, you can see apple 2 and pen 1. In drawer 3, you see nothing." Then there is 2 on/in relationships in the ground truth observation, (apple 2, countertop 1), (pen 1, countertop 1). And there is nothing in drawer 3, so there is zero on/in relationship with respect to drawer 3. If the vlm observation says "On countertop 1, you can see apple 2. In drawer 3, you can see watch 1 and pen 1." Then there is only 1 correctly identified on/in relationships in the vlm observation(apple 2, countertop 1). The score is 1/2 because only 1 out of 2 on/in relationships are correctly identified.\n'
        " - If the ground truth observation doesn't specify any on/in relationships, the score is 1 if the vlm observation doesn't mention any on/in relationships, otherwise the score is 0.\n"
        "2. If the receptacle is openable (e.g., cabinet, safe, drawer, microwave, fridge), correctness of identifying whether it is open or closed."
        " - First, list each openable receptacle from the ground truth and whether it is open or closed.\n"
        " - Then, check whether the VLM’s observation explicitly states the status of each of those openable receptacles and make a list of the correctly identified openable receptacles.\n"
        " - If the VLM fails to mention the status of a receptacle or provides an incorrect status, it is considered an incorrect identification for that receptacle.\n"
        " - The score = (number of correctly identified openable receptacles / total openable receptacles).\n"
        ' - e.g. if the ground truth observation says "the cabinet 1 is closed, the drawer 1 is open," then there are two openable receptacles in total. If the VLM says "the cabinet 1 is closed and you see drawer 1." or " the cabinet is closed." The score is (1/2) = 0.5. since the former only mentions the status of cabinet 1 correctly but misses the status of drawer 1, and the latter misses mentioning drawer 1.\n'
        " - If the ground truth observation doesn't specify the status ofany openable receptacles, the score is 1 if the vlm observation doesn't mention any openable receptacles, otherwise the score is 0.\n"
    )
    user_prompt = (
        f"**VLM’s Observation:**\n{vlm_obs}\n\n"
        f"**Ground Truth Observation:**\n{ground_truth_obs}\n\n"
        "Follow the above rules and compare the VLM's observation to the ground truth observation. Think step by step to provide a detailed explanation for your evaluation and score."
    )

    return sys_prompt, user_prompt
